version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 140220
      POSTGRES_DB: db_testing
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://atreyucam:UXwzs5wKVHtIFYZvYtWVw0oQJuDDbfiI@dpg-cp9rt5cf7o1s73a630ag-a/db_testing_9g79
